version: '2.1'
services:
  discovery: 
    image: eureka-server
    container_name: discovery
    ports: 
      - "8761:8761"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761"]
      interval: 1m
      timeout: 40s
      retries: 3
    volumes:
      - /e/CloudLogs:/appLogs
  configserver: 
    #environment: 
      #- "spring.cloud.config.label=dev"
      #- "spring.profiles.active=development"
    image: config-server
    container_name: configserver
    depends_on: 
      discovery:
        condition: service_healthy
    ports: 
      - "8888:8888"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/env"]
      interval: 1m
      timeout: 40s
      retries: 3
    volumes:
      - /e/CloudLogs:/appLogs
    links:
      - discovery
  gateway: 
    image: zuul-gateway
    container_name: gateway
    depends_on: 
      discovery:
        condition: service_healthy
      configserver:
        condition: service_healthy
    ports: 
      - "9010:9010"
    volumes:
      - /e/CloudLogs:/appLogs
    links:
      - discovery
      - configserver
      - cars
      - rentals
      - users
  users: 
    image: user-service
    container_name: users
    depends_on: 
      discovery:
        condition: service_healthy
      configserver:
        condition: service_healthy
    volumes:
      - /e/CloudLogs:/appLogs
    links:
      - discovery
      - configserver
  cars: 
    image: car-service
    container_name: cars
    depends_on: 
      discovery:
        condition: service_healthy
      configserver:
        condition: service_healthy
    volumes:
      - /e/CloudLogs:/appLogs
    links:
      - discovery
      - configserver
  rentals: 
    image: rental-service
    container_name: rentals
    depends_on: 
      discovery:
        condition: service_healthy
      configserver:
        condition: service_healthy
    volumes:
      - /e/CloudLogs:/appLogs
    links:
      - discovery
      - configserver