version: '2.1'
services:
  discovery: 
    image: eureka-server
    container_name: discovery
    ports: 
      - "8761:8761"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8761"]
      interval: 1m
      timeout: 40s
      retries: 3
  cars: 
    image: car-service
    depends_on: 
      discovery:
        condition: service_healthy
      configserver:
        condition: service_healthy
  configserver: 
    environment: 
      - "spring.cloud.config.label=dev"
      - "spring.profiles.active=development"
    image: config-server
    depends_on: 
      discovery:
        condition: service_healthy
    ports: 
      - "8888:8888"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8888/env"]
      interval: 1m
      timeout: 40s
      retries: 3
  gateway: 
    image: zuul-gateway
    depends_on: 
      discovery:
        condition: service_healthy
      configserver:
        condition: service_healthy
    ports: 
      - "9010:9010" 
  rentals: 
    image: rental-service
    depends_on: 
      discovery:
        condition: service_healthy
      configserver:
        condition: service_healthy
  users: 
    image: user-service
    depends_on: 
      discovery:
        condition: service_healthy
      configserver:
        condition: service_healthy
    