zuul:
  routes:
    user-service: /users/**
    car-service: /cars/**      
    car-orders:
      path: /orders/**
      serviceId:  rental-service
      

user-service:
  ribbon:
    eureka:
      enabled: false  

car-service:
  ribbon:
    eureka:
      enabled: false
      
rental-service:
  ribbon:
    eureka:
      enabled: false
    
server:
  port: 9010
  

endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false
    
eureka:
  instance:
    hostname: gateway
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  
