server:
  port: 8761

eureka:
  instance:
    hostname: discovery
    prefer-ip-address: true
  client:
    registerWithEureka: false
    fetchRegistry: false
   

spring.cloud.config.discovery.enabled: true